Switched styling to use material design
BenjaminPalko/tictactoe.io pull request #1
Opened 2022-10-02 15:41 UTC by BenjaminPalko

2022-10-02 17:53 UTC, piopi requested changes

2022-10-02 17:53 UTC, piopi commented on components/board.tsx
I would convert this class to a react component function
```
const Board = () => { return (...)}
```

2022-10-02 17:53 UTC, piopi commented on components/board.tsx
> +            </Box>
```suggestion
            <Box>
                <div>{status}</div>
                <Grid container spacing={1}>
                    {
                        this.state.squares.map((value, index) => (
                            <Grid item key={index} xs={4}>
                               <Square onClick={() => this.handleClick(i)} value={value} />
                            </Grid>)
                        ))
                    }
                </Grid>
            </Box>
```

I would also avoid using index a key it is considered an anti-pattern, https://robinpokorny.com/blog/index-as-a-key-is-an-anti-pattern/

2022-10-02 17:53 UTC, piopi commented on components/game.tsx
>  export default function Game(props: GameProps) {
Do you need props for later? if not you can remove them

2022-10-02 17:53 UTC, piopi commented on components/square.tsx
>  export default function Square(props: SquareProps) {
`export default function Square({onClick, value}: SquareProps)`

Destructuring will avoid using props.value

2022-10-02 17:53 UTC, piopi commented on components/square.tsx
> +        </Button>
```suggestion
        <Button
            disabled={props.value}
            variant={"outlined"}
            onClick={() => props.onClick()}
        fullWidth={true}>
            {!props.value && <Skeleton variant={"text"} width={16} animation={false} />}
            {props.value === 'X' && <Close />}
            {props.value === 'O' && <RadioButtonUnchecked />}
        </Button>
```

This one is just a preference but if you wanna use a function you should combine it with useCallback.
https://reactjs.org/docs/hooks-reference.html#usecallback

2022-10-02 17:53 UTC, piopi commented on pages/index.tsx
> +                    Tic-Tac-Toe
I would store this string a variable

2022-10-02 17:53 UTC, piopi commented on pages/index.tsx
> +                    style={{textAlign: "center"}}
Small suggestion, I would use the styled utility of Material to add CSS: https://mui.com/system/styled/ , it allows you to access your theme variable and create reusable components with the same style, you can override the style of any component or HTML tag

2022-10-02 17:53 UTC, piopi commented on styles/globals.css
> +  background-color: #3d3dcc;
color should be stored in a variable if possible

2022-10-02 17:57 UTC, piopi commented on pages/_app.tsx
> +import '@fontsource/roboto/700.css';
https://mui.com/material-ui/customization/typography/

2022-10-03 00:33 UTC, BenjaminPalko commented on components/game.tsx
>  export default function Game(props: GameProps) {
Yeah we are most definitely going to need props on Game

2022-10-07 01:25 UTC, BenjaminPalko commented on pages/index.tsx
> +                    style={{textAlign: "center"}}
Ended up just using sx on each component since they are small changes

2022-10-07 02:35 UTC, merged